### ISSUE TITLE
No se hace reset de la variable multiplo

### ISSUE THREAD

**Issue by juusechec** [Dwan13/SistemasOP#1]
Esta es solo del dominio de la función función createTable(), allí debe definirse el múltiplo como 0
https://github.com/Dwan13/SistemasOP/blob/d4b6c36f7d74c90a5d1f76ee9c17051cf8358adc/ejercicio2/js/script.js#L153

**Comment by MauricioAcosta** [comment]
Gracias!

**Comment by MauricioAcosta** [comment]
Muchas gracias! 
https://github.com/Dwan13/SistemasOP/commit/5d1c5e35a56ba9eb4cb8664510f376b219d8a626
