### ISSUE TITLE
el índice "i" no está en el dominio del setTimeout

### ISSUE THREAD

**Issue by juusechec** [Dwan13/SistemasOP#2]
Dentro del setTimeout es necesario hacer var i = this; ya que this es el único que contiene ese valor real, dentro del setTimeout el valor "i" es algo inesperado, es el último valor de i dentro de un contexto padre, o sea, no va a poder obtener el "i" esperado, en cambio "this" si lo tiene debido a que se inyecta en el momento de la creación de la función con "bind".
https://github.com/Dwan13/SistemasOP/blob/d4b6c36f7d74c90a5d1f76ee9c17051cf8358adc/ejercicio2/js/script.js#L138

**Comment by MauricioAcosta** [comment]
Toda la razón, me estaba complicando al generar otra variable :dagger:

**Comment by MauricioAcosta** [comment]
¡Muchas gracias!
https://github.com/Dwan13/SistemasOP/commit/5d1c5e35a56ba9eb4cb8664510f376b219d8a626
