### ISSUE TITLE
multiplo no tiene sentido para un solo proceso

### ISSUE THREAD

**Issue by juusechec** [Dwan13/SistemasOP#3]
quitar multiplo y reemplazarlo por el "i" del for
https://github.com/Dwan13/SistemasOP/blob/ccdd7bb54eb0ecc2237d730b3e62a884f5ed292f/ejercicio2/js/script.js#L151

**Comment by juusechec** [comment]
También removerlo de https://github.com/Dwan13/SistemasOP/blob/ccdd7bb54eb0ecc2237d730b3e62a884f5ed292f/ejercicio2/js/script.js#L122

**Comment by MauricioAcosta** [comment]
Si toda la razón, si hubiera tuviera que correr distintos procesos dentro del mismo setTimeOut, si seria necesaria la variable, pero como es un solo proceso no es necesaria, gracias ya lo resolví. https://github.com/Dwan13/SistemasOP/commit/777eee3706fc4e8115dcd2c5f5f3218634fd11b5
